use risc0_zkvm::compute_image_id;

// ELF bytes are generated by build.rs and included from OUT_DIR
include!(concat!(env!("OUT_DIR"), "/methods.rs"));

lazy_static::lazy_static! {
    pub static ref RISC0_VERIFIER_ID: [u32; 8] = compute_image_id(RISC0_VERIFIER_ELF)
        .expect("Failed to compute RISC0_VERIFIER_ID")
        .as_words()
        .try_into()
        .expect("Image ID should be 8 words");
}
